"""Tests for dimljus.video.probe — requires ffprobe in PATH.

Tests are skipped automatically if ffprobe is not available.
Uses tiny test videos generated by conftest.py fixtures.
"""

from pathlib import Path

import pytest

from tests.conftest import requires_ffmpeg

from dimljus.video.errors import FFmpegNotFoundError, ProbeError
from dimljus.video.probe import (
    _parse_frame_rate,
    _parse_sar,
    probe_directory,
    probe_video,
)


# ---------------------------------------------------------------------------
# Unit tests — no ffprobe needed
# ---------------------------------------------------------------------------

class TestParseFrameRate:
    """Tests for frame rate string parsing."""

    def test_fraction(self) -> None:
        assert _parse_frame_rate("30/1") == 30.0

    def test_ntsc(self) -> None:
        """23.976 fps = 24000/1001."""
        assert abs(_parse_frame_rate("24000/1001") - 23.976) < 0.001

    def test_plain_float(self) -> None:
        assert _parse_frame_rate("16.0") == 16.0

    def test_invalid(self) -> None:
        assert _parse_frame_rate("invalid") == 0.0

    def test_zero_denominator(self) -> None:
        assert _parse_frame_rate("30/0") == 0.0


class TestParseSAR:
    """Tests for SAR string normalization."""

    def test_colon_format(self) -> None:
        assert _parse_sar("1:1") == "1:1"

    def test_slash_format(self) -> None:
        assert _parse_sar("1/1") == "1:1"

    def test_non_square(self) -> None:
        assert _parse_sar("4:3") == "4:3"

    def test_na(self) -> None:
        assert _parse_sar("N/A") == "1:1"

    def test_none(self) -> None:
        assert _parse_sar(None) == "1:1"

    def test_zero(self) -> None:
        assert _parse_sar("0:0") == "1:1"


# ---------------------------------------------------------------------------
# Integration tests — require ffprobe
# ---------------------------------------------------------------------------

@requires_ffmpeg
class TestProbeVideo:
    """Tests for probing video files via ffprobe."""

    def test_probe_tiny_video(self, tiny_video: Path) -> None:
        """Probe a simple test video and check metadata."""
        meta = probe_video(tiny_video)

        assert meta.path == tiny_video.resolve()
        assert meta.width == 320
        assert meta.height == 240
        assert abs(meta.fps - 16.0) < 0.5
        assert meta.frame_count > 0
        assert meta.duration > 0
        assert meta.codec in ("h264", "libx264")
        assert meta.pix_fmt == "yuv420p"

    def test_probe_nonexistent(self, tmp_path: Path) -> None:
        """Probing nonexistent file raises ProbeError."""
        with pytest.raises(ProbeError, match="does not exist"):
            probe_video(tmp_path / "nonexistent.mp4")

    def test_probe_not_a_video(self, tmp_path: Path) -> None:
        """Probing a text file raises ProbeError."""
        text_file = tmp_path / "not_video.txt"
        text_file.write_text("hello world")
        with pytest.raises(ProbeError):
            probe_video(text_file)

    def test_probe_directory_raises(self, tmp_path: Path) -> None:
        """Probing a directory raises ProbeError."""
        with pytest.raises(ProbeError, match="not a file"):
            probe_video(tmp_path)

    def test_probe_720p(self, tiny_video_720p: Path) -> None:
        """Probe a 720p video."""
        meta = probe_video(tiny_video_720p)
        assert meta.height == 720
        assert meta.width == 1280

    def test_probe_30fps(self, tiny_video_30fps: Path) -> None:
        """Probe a 30fps video."""
        meta = probe_video(tiny_video_30fps)
        assert abs(meta.fps - 30.0) < 0.5


@requires_ffmpeg
class TestProbeDirectory:
    """Tests for scanning a directory of videos."""

    def test_probe_directory(self, tiny_video: Path) -> None:
        """Probe a directory with one video."""
        results = probe_directory(tiny_video.parent)
        assert len(results) >= 1
        assert any(r.path == tiny_video.resolve() for r in results)

    def test_probe_empty_directory(self, tmp_path: Path) -> None:
        """Empty directory returns empty list."""
        results = probe_directory(tmp_path)
        assert results == []

    def test_probe_nonexistent_directory(self) -> None:
        """Nonexistent directory raises FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            probe_directory("/nonexistent/path")

    def test_probe_skips_non_video(self, tmp_path: Path) -> None:
        """Non-video files are ignored."""
        (tmp_path / "readme.txt").write_text("hello")
        (tmp_path / "data.json").write_text("{}")
        results = probe_directory(tmp_path)
        assert results == []
