name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Copied CLAUDE.md into empty directory
        2. Opened Claude Code
        3. ...
    validations:
      required: true
  - type: input
    id: claude-version
    attributes:
      label: Claude Code version
      placeholder: e.g. 2.1.47
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g. macOS 15.2, Windows 11, Ubuntu 24.04
